version: "3.9"

services:
  web:
    container_name: dev_web
    restart: always
    build:
      context: ./../..
      dockerfile: deployments/docker/web/Dockerfile
    ports:
      - "3000:3000"
    expose:
      - "3000"
